name: RELEASE

on:
  push:
    tags:
      - '*'

jobs:

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6

      - name: Publish docs
        run: sbt "project docs" clean makeSite ghpagesPushSite
